package com.yuhan123.vulkanmod.mixin.texture;

import com.google.common.hash.Hashing;
import com.mojang.authlib.GameProfile;
import net.minecraft.client.ClientBrandRetriever;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.profiler.Snooper;
import net.minecraft.util.Session;
import org.apache.commons.io.Charsets;
import org.spongepowered.asm.mixin.Final;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Overwrite;
import org.spongepowered.asm.mixin.Shadow;

@Mixin(Minecraft.class)
public class MinecraftMixin {
    @Shadow @Final
    Session session;
//    @Inject(method = "getGLMaximumTextureSize", at = @At("HEAD"), cancellable = true)
//    private static void getGLMaximumTextureSize(CallbackInfoReturnable<Integer> cir) {
//        cir.setReturnValue(8192);
//    }
public boolean GL_AMD_blend_minmax_factor;
    public boolean GL_AMD_conservative_depth;
    public boolean GL_AMD_debug_output;
    public boolean GL_AMD_depth_clamp_separate;
    public boolean GL_AMD_draw_buffers_blend;
    public boolean GL_AMD_interleaved_elements;
    public boolean GL_AMD_multi_draw_indirect;
    public boolean GL_AMD_name_gen_delete;
    public boolean GL_AMD_performance_monitor;
    public boolean GL_AMD_pinned_memory;
    public boolean GL_AMD_query_buffer_object;
    public boolean GL_AMD_sample_positions;
    public boolean GL_AMD_seamless_cubemap_per_texture;
    public boolean GL_AMD_shader_atomic_counter_ops;
    public boolean GL_AMD_shader_stencil_export;
    public boolean GL_AMD_shader_trinary_minmax;
    public boolean GL_AMD_sparse_texture;
    public boolean GL_AMD_stencil_operation_extended;
    public boolean GL_AMD_texture_texture4;
    public boolean GL_AMD_transform_feedback3_lines_triangles;
    public boolean GL_AMD_vertex_shader_layer;
    public boolean GL_AMD_vertex_shader_tessellator;
    public boolean GL_AMD_vertex_shader_viewport_index;
    public boolean GL_APPLE_aux_depth_stencil;
    public boolean GL_APPLE_client_storage;
    public boolean GL_APPLE_element_array;
    public boolean GL_APPLE_fence;
    public boolean GL_APPLE_float_pixels;
    public boolean GL_APPLE_flush_buffer_range;
    public boolean GL_APPLE_object_purgeable;
    public boolean GL_APPLE_packed_pixels;
    public boolean GL_APPLE_rgb_422;
    public boolean GL_APPLE_row_bytes;
    public boolean GL_APPLE_texture_range;
    public boolean GL_APPLE_vertex_array_object;
    public boolean GL_APPLE_vertex_array_range;
    public boolean GL_APPLE_vertex_program_evaluators;
    public boolean GL_APPLE_ycbcr_422;
    public boolean GL_ARB_ES2_compatibility;
    public boolean GL_ARB_ES3_1_compatibility;
    public boolean GL_ARB_ES3_compatibility;
    public boolean GL_ARB_arrays_of_arrays;
    public boolean GL_ARB_base_instance;
    public boolean GL_ARB_bindless_texture;
    public boolean GL_ARB_blend_func_extended;
    public boolean GL_ARB_buffer_storage;
    public boolean GL_ARB_cl_event;
    public boolean GL_ARB_clear_buffer_object;
    public boolean GL_ARB_clear_texture;
    public boolean GL_ARB_clip_control;
    public boolean GL_ARB_color_buffer_float;
    public boolean GL_ARB_compatibility;
    public boolean GL_ARB_compressed_texture_pixel_storage;
    public boolean GL_ARB_compute_shader;
    public boolean GL_ARB_compute_variable_group_size;
    public boolean GL_ARB_conditional_render_inverted;
    public boolean GL_ARB_conservative_depth;
    public boolean GL_ARB_copy_buffer;
    public boolean GL_ARB_copy_image;
    public boolean GL_ARB_cull_distance;
    public boolean GL_ARB_debug_output;
    public boolean GL_ARB_depth_buffer_float;
    public boolean GL_ARB_depth_clamp;
    public boolean GL_ARB_depth_texture;
    public boolean GL_ARB_derivative_control;
    public boolean GL_ARB_direct_state_access;
    public boolean GL_ARB_draw_buffers;
    public boolean GL_ARB_draw_buffers_blend;
    public boolean GL_ARB_draw_elements_base_vertex;
    public boolean GL_ARB_draw_indirect;
    public boolean GL_ARB_draw_instanced;
    public boolean GL_ARB_enhanced_layouts;
    public boolean GL_ARB_explicit_attrib_location;
    public boolean GL_ARB_explicit_uniform_location;
    public boolean GL_ARB_fragment_coord_conventions;
    public boolean GL_ARB_fragment_layer_viewport;
    public boolean GL_ARB_fragment_program;
    public boolean GL_ARB_fragment_program_shadow;
    public boolean GL_ARB_fragment_shader;
    public boolean GL_ARB_framebuffer_no_attachments;
    public boolean GL_ARB_framebuffer_object;
    public boolean GL_ARB_framebuffer_sRGB;
    public boolean GL_ARB_geometry_shader4;
    public boolean GL_ARB_get_program_binary;
    public boolean GL_ARB_get_texture_sub_image;
    public boolean GL_ARB_gpu_shader5;
    public boolean GL_ARB_gpu_shader_fp64;
    public boolean GL_ARB_half_float_pixel;
    public boolean GL_ARB_half_float_vertex;
    public boolean GL_ARB_imaging;
    public boolean GL_ARB_indirect_parameters;
    public boolean GL_ARB_instanced_arrays;
    public boolean GL_ARB_internalformat_query;
    public boolean GL_ARB_internalformat_query2;
    public boolean GL_ARB_invalidate_subdata;
    public boolean GL_ARB_map_buffer_alignment;
    public boolean GL_ARB_map_buffer_range;
    public boolean GL_ARB_matrix_palette;
    public boolean GL_ARB_multi_bind;
    public boolean GL_ARB_multi_draw_indirect;
    public boolean GL_ARB_multisample;
    public boolean GL_ARB_multitexture;
    public boolean GL_ARB_occlusion_query;
    public boolean GL_ARB_occlusion_query2;
    public boolean GL_ARB_pipeline_statistics_query;
    public boolean GL_ARB_pixel_buffer_object;
    public boolean GL_ARB_point_parameters;
    public boolean GL_ARB_point_sprite;
    public boolean GL_ARB_program_interface_query;
    public boolean GL_ARB_provoking_vertex;
    public boolean GL_ARB_query_buffer_object;
    public boolean GL_ARB_robust_buffer_access_behavior;
    public boolean GL_ARB_robustness;
    public boolean GL_ARB_robustness_isolation;
    public boolean GL_ARB_sample_shading;
    public boolean GL_ARB_sampler_objects;
    public boolean GL_ARB_seamless_cube_map;
    public boolean GL_ARB_seamless_cubemap_per_texture;
    public boolean GL_ARB_separate_shader_objects;
    public boolean GL_ARB_shader_atomic_counters;
    public boolean GL_ARB_shader_bit_encoding;
    public boolean GL_ARB_shader_draw_parameters;
    public boolean GL_ARB_shader_group_vote;
    public boolean GL_ARB_shader_image_load_store;
    public boolean GL_ARB_shader_image_size;
    public boolean GL_ARB_shader_objects;
    public boolean GL_ARB_shader_precision;
    public boolean GL_ARB_shader_stencil_export;
    public boolean GL_ARB_shader_storage_buffer_object;
    public boolean GL_ARB_shader_subroutine;
    public boolean GL_ARB_shader_texture_image_samples;
    public boolean GL_ARB_shader_texture_lod;
    public boolean GL_ARB_shading_language_100;
    public boolean GL_ARB_shading_language_420pack;
    public boolean GL_ARB_shading_language_include;
    public boolean GL_ARB_shading_language_packing;
    public boolean GL_ARB_shadow;
    public boolean GL_ARB_shadow_ambient;
    public boolean GL_ARB_sparse_buffer;
    public boolean GL_ARB_sparse_texture;
    public boolean GL_ARB_stencil_texturing;
    public boolean GL_ARB_sync;
    public boolean GL_ARB_tessellation_shader;
    public boolean GL_ARB_texture_barrier;
    public boolean GL_ARB_texture_border_clamp;
    public boolean GL_ARB_texture_buffer_object;
    public boolean GL_ARB_texture_buffer_object_rgb32;
    public boolean GL_ARB_texture_buffer_range;
    public boolean GL_ARB_texture_compression;
    public boolean GL_ARB_texture_compression_bptc;
    public boolean GL_ARB_texture_compression_rgtc;
    public boolean GL_ARB_texture_cube_map;
    public boolean GL_ARB_texture_cube_map_array;
    public boolean GL_ARB_texture_env_add;
    public boolean GL_ARB_texture_env_combine;
    public boolean GL_ARB_texture_env_crossbar;
    public boolean GL_ARB_texture_env_dot3;
    public boolean GL_ARB_texture_float;
    public boolean GL_ARB_texture_gather;
    public boolean GL_ARB_texture_mirror_clamp_to_edge;
    public boolean GL_ARB_texture_mirrored_repeat;
    public boolean GL_ARB_texture_multisample;
    public boolean GL_ARB_texture_non_power_of_two;
    public boolean GL_ARB_texture_query_levels;
    public boolean GL_ARB_texture_query_lod;
    public boolean GL_ARB_texture_rectangle;
    public boolean GL_ARB_texture_rg;
    public boolean GL_ARB_texture_rgb10_a2ui;
    public boolean GL_ARB_texture_stencil8;
    public boolean GL_ARB_texture_storage;
    public boolean GL_ARB_texture_storage_multisample;
    public boolean GL_ARB_texture_swizzle;
    public boolean GL_ARB_texture_view;
    public boolean GL_ARB_timer_query;
    public boolean GL_ARB_transform_feedback2;
    public boolean GL_ARB_transform_feedback3;
    public boolean GL_ARB_transform_feedback_instanced;
    public boolean GL_ARB_transform_feedback_overflow_query;
    public boolean GL_ARB_transpose_matrix;
    public boolean GL_ARB_uniform_buffer_object;
    public boolean GL_ARB_vertex_array_bgra;
    public boolean GL_ARB_vertex_array_object;
    public boolean GL_ARB_vertex_attrib_64bit;
    public boolean GL_ARB_vertex_attrib_binding;
    public boolean GL_ARB_vertex_blend;
    public boolean GL_ARB_vertex_buffer_object;
    public boolean GL_ARB_vertex_program;
    public boolean GL_ARB_vertex_shader;
    public boolean GL_ARB_vertex_type_10f_11f_11f_rev;
    public boolean GL_ARB_vertex_type_2_10_10_10_rev;
    public boolean GL_ARB_viewport_array;
    public boolean GL_ARB_window_pos;
    public boolean GL_ATI_draw_buffers;
    public boolean GL_ATI_element_array;
    public boolean GL_ATI_envmap_bumpmap;
    public boolean GL_ATI_fragment_shader;
    public boolean GL_ATI_map_object_buffer;
    public boolean GL_ATI_meminfo;
    public boolean GL_ATI_pn_triangles;
    public boolean GL_ATI_separate_stencil;
    public boolean GL_ATI_shader_texture_lod;
    public boolean GL_ATI_text_fragment_shader;
    public boolean GL_ATI_texture_compression_3dc;
    public boolean GL_ATI_texture_env_combine3;
    public boolean GL_ATI_texture_float;
    public boolean GL_ATI_texture_mirror_once;
    public boolean GL_ATI_vertex_array_object;
    public boolean GL_ATI_vertex_attrib_array_object;
    public boolean GL_ATI_vertex_streams;
    public boolean GL_EXT_Cg_shader;
    public boolean GL_EXT_abgr;
    public boolean GL_EXT_bgra;
    public boolean GL_EXT_bindable_uniform;
    public boolean GL_EXT_blend_color;
    public boolean GL_EXT_blend_equation_separate;
    public boolean GL_EXT_blend_func_separate;
    public boolean GL_EXT_blend_minmax;
    public boolean GL_EXT_blend_subtract;
    public boolean GL_EXT_compiled_vertex_array;
    public boolean GL_EXT_depth_bounds_test;
    public boolean GL_EXT_direct_state_access;
    public boolean GL_EXT_draw_buffers2;
    public boolean GL_EXT_draw_instanced;
    public boolean GL_EXT_draw_range_elements;
    public boolean GL_EXT_fog_coord;
    public boolean GL_EXT_framebuffer_blit;
    public boolean GL_EXT_framebuffer_multisample;
    public boolean GL_EXT_framebuffer_multisample_blit_scaled;
    public boolean GL_EXT_framebuffer_object;
    public boolean GL_EXT_framebuffer_sRGB;
    public boolean GL_EXT_geometry_shader4;
    public boolean GL_EXT_gpu_program_parameters;
    public boolean GL_EXT_gpu_shader4;
    public boolean GL_EXT_multi_draw_arrays;
    public boolean GL_EXT_packed_depth_stencil;
    public boolean GL_EXT_packed_float;
    public boolean GL_EXT_packed_pixels;
    public boolean GL_EXT_paletted_texture;
    public boolean GL_EXT_pixel_buffer_object;
    public boolean GL_EXT_point_parameters;
    public boolean GL_EXT_provoking_vertex;
    public boolean GL_EXT_rescale_normal;
    public boolean GL_EXT_secondary_color;
    public boolean GL_EXT_separate_shader_objects;
    public boolean GL_EXT_separate_specular_color;
    public boolean GL_EXT_shader_image_load_store;
    public boolean GL_EXT_shadow_funcs;
    public boolean GL_EXT_shared_texture_palette;
    public boolean GL_EXT_stencil_clear_tag;
    public boolean GL_EXT_stencil_two_side;
    public boolean GL_EXT_stencil_wrap;
    public boolean GL_EXT_texture_3d;
    public boolean GL_EXT_texture_array;
    public boolean GL_EXT_texture_buffer_object;
    public boolean GL_EXT_texture_compression_latc;
    public boolean GL_EXT_texture_compression_rgtc;
    public boolean GL_EXT_texture_compression_s3tc;
    public boolean GL_EXT_texture_env_combine;
    public boolean GL_EXT_texture_env_dot3;
    public boolean GL_EXT_texture_filter_anisotropic;
    public boolean GL_EXT_texture_integer;
    public boolean GL_EXT_texture_lod_bias;
    public boolean GL_EXT_texture_mirror_clamp;
    public boolean GL_EXT_texture_rectangle;
    public boolean GL_EXT_texture_sRGB;
    public boolean GL_EXT_texture_sRGB_decode;
    public boolean GL_EXT_texture_shared_exponent;
    public boolean GL_EXT_texture_snorm;
    public boolean GL_EXT_texture_swizzle;
    public boolean GL_EXT_timer_query;
    public boolean GL_EXT_transform_feedback;
    public boolean GL_EXT_vertex_array_bgra;
    public boolean GL_EXT_vertex_attrib_64bit;
    public boolean GL_EXT_vertex_shader;
    public boolean GL_EXT_vertex_weighting;

    @Overwrite
    public void addServerTypeToSnooper(Snooper p_70001_1_) {
        p_70001_1_.addStatToSnooper("opengl_version", GlStateManager.glGetString(7938));
        p_70001_1_.addStatToSnooper("opengl_vendor", GlStateManager.glGetString(7936));
        p_70001_1_.addStatToSnooper("client_brand", ClientBrandRetriever.getClientModName());
        p_70001_1_.addStatToSnooper("launched_version", 0);
//        ContextCapabilities contextcapabilities = GLContext.getCapabilities();
        p_70001_1_.addStatToSnooper("gl_caps[ARB_arrays_of_arrays]", GL_ARB_arrays_of_arrays);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_base_instance]", GL_ARB_base_instance);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_blend_func_extended]", GL_ARB_blend_func_extended);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_clear_buffer_object]", GL_ARB_clear_buffer_object);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_color_buffer_float]", GL_ARB_color_buffer_float);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_compatibility]", GL_ARB_compatibility);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_compressed_texture_pixel_storage]", GL_ARB_compressed_texture_pixel_storage);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_compute_shader]", GL_ARB_compute_shader);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_copy_buffer]", GL_ARB_copy_buffer);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_copy_image]", GL_ARB_copy_image);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_depth_buffer_float]", GL_ARB_depth_buffer_float);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_compute_shader]", GL_ARB_compute_shader);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_copy_buffer]", GL_ARB_copy_buffer);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_copy_image]", GL_ARB_copy_image);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_depth_buffer_float]", GL_ARB_depth_buffer_float);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_depth_clamp]", GL_ARB_depth_clamp);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_depth_texture]", GL_ARB_depth_texture);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_draw_buffers]", GL_ARB_draw_buffers);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_draw_buffers_blend]", GL_ARB_draw_buffers_blend);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_draw_elements_base_vertex]", GL_ARB_draw_elements_base_vertex);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_draw_indirect]", GL_ARB_draw_indirect);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_draw_instanced]", GL_ARB_draw_instanced);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_explicit_attrib_location]", GL_ARB_explicit_attrib_location);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_explicit_uniform_location]", GL_ARB_explicit_uniform_location);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_fragment_layer_viewport]", GL_ARB_fragment_layer_viewport);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_fragment_program]", GL_ARB_fragment_program);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_fragment_shader]", GL_ARB_fragment_shader);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_fragment_program_shadow]", GL_ARB_fragment_program_shadow);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_framebuffer_object]", GL_ARB_framebuffer_object);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_framebuffer_sRGB]", GL_ARB_framebuffer_sRGB);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_geometry_shader4]", GL_ARB_geometry_shader4);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_gpu_shader5]", GL_ARB_gpu_shader5);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_half_float_pixel]", GL_ARB_half_float_pixel);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_half_float_vertex]", GL_ARB_half_float_vertex);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_instanced_arrays]", GL_ARB_instanced_arrays);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_map_buffer_alignment]", GL_ARB_map_buffer_alignment);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_map_buffer_range]", GL_ARB_map_buffer_range);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_multisample]", GL_ARB_multisample);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_multitexture]", GL_ARB_multitexture);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_occlusion_query2]", GL_ARB_occlusion_query2);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_pixel_buffer_object]", GL_ARB_pixel_buffer_object);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_seamless_cube_map]", GL_ARB_seamless_cube_map);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_shader_objects]", GL_ARB_shader_objects);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_shader_stencil_export]", GL_ARB_shader_stencil_export);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_shader_texture_lod]", GL_ARB_shader_texture_lod);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_shadow]", GL_ARB_shadow);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_shadow_ambient]", GL_ARB_shadow_ambient);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_stencil_texturing]", GL_ARB_stencil_texturing);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_sync]", GL_ARB_sync);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_tessellation_shader]", GL_ARB_tessellation_shader);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_texture_border_clamp]", GL_ARB_texture_border_clamp);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_texture_buffer_object]", GL_ARB_texture_buffer_object);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_texture_cube_map]", GL_ARB_texture_cube_map);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_texture_cube_map_array]", GL_ARB_texture_cube_map_array);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_texture_non_power_of_two]", GL_ARB_texture_non_power_of_two);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_uniform_buffer_object]", GL_ARB_uniform_buffer_object);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_vertex_blend]", GL_ARB_vertex_blend);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_vertex_buffer_object]", GL_ARB_vertex_buffer_object);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_vertex_program]", GL_ARB_vertex_program);
        p_70001_1_.addStatToSnooper("gl_caps[ARB_vertex_shader]", GL_ARB_vertex_shader);
        p_70001_1_.addStatToSnooper("gl_caps[EXT_bindable_uniform]", GL_EXT_bindable_uniform);
        p_70001_1_.addStatToSnooper("gl_caps[EXT_blend_equation_separate]", GL_EXT_blend_equation_separate);
        p_70001_1_.addStatToSnooper("gl_caps[EXT_blend_func_separate]", GL_EXT_blend_func_separate);
        p_70001_1_.addStatToSnooper("gl_caps[EXT_blend_minmax]", GL_EXT_blend_minmax);
        p_70001_1_.addStatToSnooper("gl_caps[EXT_blend_subtract]", GL_EXT_blend_subtract);
        p_70001_1_.addStatToSnooper("gl_caps[EXT_draw_instanced]", GL_EXT_draw_instanced);
        p_70001_1_.addStatToSnooper("gl_caps[EXT_framebuffer_multisample]", GL_EXT_framebuffer_multisample);
        p_70001_1_.addStatToSnooper("gl_caps[EXT_framebuffer_object]", GL_EXT_framebuffer_object);
        p_70001_1_.addStatToSnooper("gl_caps[EXT_framebuffer_sRGB]", GL_EXT_framebuffer_sRGB);
        p_70001_1_.addStatToSnooper("gl_caps[EXT_geometry_shader4]", GL_EXT_geometry_shader4);
        p_70001_1_.addStatToSnooper("gl_caps[EXT_gpu_program_parameters]", GL_EXT_gpu_program_parameters);
        p_70001_1_.addStatToSnooper("gl_caps[EXT_gpu_shader4]", GL_EXT_gpu_shader4);
        p_70001_1_.addStatToSnooper("gl_caps[EXT_multi_draw_arrays]", GL_EXT_multi_draw_arrays);
        p_70001_1_.addStatToSnooper("gl_caps[EXT_packed_depth_stencil]", GL_EXT_packed_depth_stencil);
        p_70001_1_.addStatToSnooper("gl_caps[EXT_paletted_texture]", GL_EXT_paletted_texture);
        p_70001_1_.addStatToSnooper("gl_caps[EXT_rescale_normal]", GL_EXT_rescale_normal);
        p_70001_1_.addStatToSnooper("gl_caps[EXT_separate_shader_objects]", GL_EXT_separate_shader_objects);
        p_70001_1_.addStatToSnooper("gl_caps[EXT_shader_image_load_store]", GL_EXT_shader_image_load_store);
        p_70001_1_.addStatToSnooper("gl_caps[EXT_shadow_funcs]", GL_EXT_shadow_funcs);
        p_70001_1_.addStatToSnooper("gl_caps[EXT_shared_texture_palette]", GL_EXT_shared_texture_palette);
        p_70001_1_.addStatToSnooper("gl_caps[EXT_stencil_clear_tag]", GL_EXT_stencil_clear_tag);
        p_70001_1_.addStatToSnooper("gl_caps[EXT_stencil_two_side]", GL_EXT_stencil_two_side);
        p_70001_1_.addStatToSnooper("gl_caps[EXT_stencil_wrap]", GL_EXT_stencil_wrap);
        p_70001_1_.addStatToSnooper("gl_caps[EXT_texture_3d]", GL_EXT_texture_3d);
        p_70001_1_.addStatToSnooper("gl_caps[EXT_texture_array]", GL_EXT_texture_array);
        p_70001_1_.addStatToSnooper("gl_caps[EXT_texture_buffer_object]", GL_EXT_texture_buffer_object);
        p_70001_1_.addStatToSnooper("gl_caps[EXT_texture_integer]", GL_EXT_texture_integer);
        p_70001_1_.addStatToSnooper("gl_caps[EXT_texture_lod_bias]", GL_EXT_texture_lod_bias);
        p_70001_1_.addStatToSnooper("gl_caps[EXT_texture_sRGB]", GL_EXT_texture_sRGB);
        p_70001_1_.addStatToSnooper("gl_caps[EXT_vertex_shader]", GL_EXT_vertex_shader);
        p_70001_1_.addStatToSnooper("gl_caps[EXT_vertex_weighting]", GL_EXT_vertex_weighting);
        p_70001_1_.addStatToSnooper("gl_caps[gl_max_vertex_uniforms]", GlStateManager.glGetInteger(35658));
        GlStateManager.glGetError();
        p_70001_1_.addStatToSnooper("gl_caps[gl_max_fragment_uniforms]", GlStateManager.glGetInteger(35657));
        GlStateManager.glGetError();
        p_70001_1_.addStatToSnooper("gl_caps[gl_max_vertex_attribs]", GlStateManager.glGetInteger(34921));
        GlStateManager.glGetError();
        p_70001_1_.addStatToSnooper("gl_caps[gl_max_vertex_texture_image_units]", GlStateManager.glGetInteger(35660));
        GlStateManager.glGetError();
        p_70001_1_.addStatToSnooper("gl_caps[gl_max_texture_image_units]", GlStateManager.glGetInteger(34930));
        GlStateManager.glGetError();
        p_70001_1_.addStatToSnooper("gl_caps[gl_max_array_texture_layers]", GlStateManager.glGetInteger(35071));
        GlStateManager.glGetError();
        p_70001_1_.addStatToSnooper("gl_max_texture_size", 8192);
        GameProfile gameprofile = this.session.getProfile();
        if (gameprofile != null && gameprofile.getId() != null) {
            p_70001_1_.addStatToSnooper("uuid", Hashing.sha1().hashBytes(gameprofile.getId().toString().getBytes(Charsets.ISO_8859_1)).toString());
        }
    }

//    @ModifyArg(method = "addServerTypeToSnooper", at = @At(value = "INVOKE", target = "Lnet/minecraft/profiler/Snooper;addStatToSnooper(Ljava/lang/String;Ljava/lang/Object;)V"), index = 1)
//    public Object add(Object p_152767_2_) {
//        return false;
//    }
//    @Redirect(method = "runGameLoop", at = @At(value = "INVOKE", target = "Lnet/minecraft/client/Minecraft;isFramerateLimitBelowMax()Z"))
//    public boolean isRunning(Minecraft instance) {
//        return false;
//    }
}
